[book]
authors = ["willfreee"]
language = "en"
multilingual = false
src = "src"
title = "The Easy Way to Quit YouTube Addiction"

[output.html]
git-repository-url = "https://github.com/willfreee/youtube-addiction"
edit-url-template = "https://github.com/willfreee/youtube-addiction/edit/main/src/{path}"